import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#248A3D",
  },
  header: {
    height: 100,
    backgroundColor: "#248A3D",
  },
  authContainer: {
    flex: 1,
    marginTop: 50,
    padding: 20,
    backgroundColor: "#fff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    elevation: 10,
    shadowColor: "#000",
  },
  title: {
    color: "#248A3D",
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "left",
  },
  description: {
    color: "#000000",
    fontSize: 14,
    fontWeight: "regular",
    textAlign: "left",
    marginBottom: 30,
    marginTop: 10
  },
  input: {
    height: 50,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  submitButton: {
    backgroundColor: "#248A3D",
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: "center",
  },
  submitText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  actionLeftContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginBottom: 40,
    gap: 10,
    alignItems: "center",
  },
  actionRightContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 40,
    gap: 10,
    alignItems: "center",
  },
  actionWrapContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    flexWrap: "wrap",
    width: "100%",
    marginBottom: 40,
    gap: 10,
    alignItems: "center",
  },
  link: {
    color: "#248A3D",
    fontSize: 14,
    textDecorationLine: "underline",
  },
  descText: {
    textAlign: "center",
    color: "#aaa",
    marginTop: 60,
    fontSize: 14,
  },
  socialLoginContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 20,
  },
  socialButton: {
    flex: 1,
    backgroundColor: "#F5F5F5",
    paddingVertical: 10,
    marginHorizontal: 5,
    borderRadius: 5,
    alignItems: "center",
  },
  socialButtonText: {
    fontSize: 14,
    color: "#555",
  },
  linkCenter: {
    color: "#248A3D",
    fontSize: 14,
    textAlign: "center",
    textDecorationLine: "underline",
    marginTop: 10,
  },
  checkboxContainer: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: "#248A3D",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "100%",
  },
  checkboxButton: {
    width: 12,
    height: 12,
    backgroundColor: "#248A3D",
    borderRadius: "100%",
    borderWidth: 2,
    borderColor: "#fff",
  },
  validButton: {
    backgroundColor: "#F5F5F5",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 25,
    alignItems: "center",
  },
  validButtonText: {
    fontSize: 10,
    color: "#555",
  },
  otpContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  otpInput: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderColor: "#aaa",
    borderRadius: 5,
    textAlign: "center",
    fontSize: 18,
  },
  timerText: {
    fontSize: 14,
    color: "#aaa",
    textAlign: "right",
  },
});
